Neos:
  Neos:
    fusion:
      autoInclude:
        "Sandstorm.CookiePunch": true
  Fusion:
    defaultContext:
      "CookiePunch": Sandstorm\CookiePunch\Eel\Helper\CookiePunch
      "CookiePunchConfig": Sandstorm\CookiePunch\Eel\Helper\CookiePunchConfig
Sandstorm:
  CookiePunch:
    consent:
      privacyPolicyUrl: /privacy
      elementID: "klaro"
      noAutoLoad: false
      htmlTexts: false
      embedded: false
      groupByPurpose: true
      storageMethod: cookie
      cookieName: cookie_punch
      cookieExpiresAfterDays: 120
      default: false
      mustConsent: true
      acceptAll: true
      hideDeclineAll: false
      hideLearnMore: false
      noticeAsModal: false
      disablePoweredBy: false
      additionalClass: ~
      # NOTICE: This is not Klaro API. We added this feature to CookiePunch only.
      contextualConsentOnly: false
##########################################################
# All tags specified like using the Eel Helper
# e.g. `CookiePunch.blockTags(["iframe","script", "img"]`
# will be blocked on default. You can change the default blocking behaviour
# with this configuration.
#
# Sandstorm:
#   CookiePunch:
#     blocking:
#       tagPatterns:
#         img:
#           "*":
#             block: false
#           "tracking-pixel-url":
#             service: myservice
#
##########################################################
